export type Difficulty = 'easy' | 'medium' | 'hard'

export type FlagCountry = {
  name: string
  code: string
  difficulty: Difficulty
}

export const difficultyPoints: Record<Difficulty, number> = {
  easy: 10,
  medium: 20,
  hard: 30,
}

export const countries: FlagCountry[] = [
  { name: 'United States', code: 'US', difficulty: 'easy' },
  { name: 'Canada', code: 'CA', difficulty: 'easy' },
  { name: 'Mexico', code: 'MX', difficulty: 'easy' },
  { name: 'Brazil', code: 'BR', difficulty: 'easy' },
  { name: 'Argentina', code: 'AR', difficulty: 'easy' },
  { name: 'Chile', code: 'CL', difficulty: 'medium' },
  { name: 'Colombia', code: 'CO', difficulty: 'medium' },
  { name: 'Peru', code: 'PE', difficulty: 'medium' },
  { name: 'United Kingdom', code: 'GB', difficulty: 'easy' },
  { name: 'Ireland', code: 'IE', difficulty: 'medium' },
  { name: 'France', code: 'FR', difficulty: 'easy' },
  { name: 'Germany', code: 'DE', difficulty: 'easy' },
  { name: 'Italy', code: 'IT', difficulty: 'easy' },
  { name: 'Spain', code: 'ES', difficulty: 'easy' },
  { name: 'Portugal', code: 'PT', difficulty: 'medium' },
  { name: 'Netherlands', code: 'NL', difficulty: 'medium' },
  { name: 'Belgium', code: 'BE', difficulty: 'medium' },
  { name: 'Switzerland', code: 'CH', difficulty: 'medium' },
  { name: 'Austria', code: 'AT', difficulty: 'medium' },
  { name: 'Poland', code: 'PL', difficulty: 'medium' },
  { name: 'Sweden', code: 'SE', difficulty: 'medium' },
  { name: 'Norway', code: 'NO', difficulty: 'medium' },
  { name: 'Denmark', code: 'DK', difficulty: 'medium' },
  { name: 'Finland', code: 'FI', difficulty: 'medium' },
  { name: 'Iceland', code: 'IS', difficulty: 'hard' },
  { name: 'Russia', code: 'RU', difficulty: 'easy' },
  { name: 'Ukraine', code: 'UA', difficulty: 'medium' },
  { name: 'Turkey', code: 'TR', difficulty: 'medium' },
  { name: 'Greece', code: 'GR', difficulty: 'medium' },
  { name: 'Egypt', code: 'EG', difficulty: 'easy' },
  { name: 'Morocco', code: 'MA', difficulty: 'medium' },
  { name: 'Algeria', code: 'DZ', difficulty: 'hard' },
  { name: 'Nigeria', code: 'NG', difficulty: 'easy' },
  { name: 'Kenya', code: 'KE', difficulty: 'medium' },
  { name: 'South Africa', code: 'ZA', difficulty: 'easy' },
  { name: 'Ethiopia', code: 'ET', difficulty: 'hard' },
  { name: 'Saudi Arabia', code: 'SA', difficulty: 'easy' },
  { name: 'United Arab Emirates', code: 'AE', difficulty: 'easy' },
  { name: 'Qatar', code: 'QA', difficulty: 'medium' },
  { name: 'Iran', code: 'IR', difficulty: 'medium' },
  { name: 'India', code: 'IN', difficulty: 'easy' },
  { name: 'Pakistan', code: 'PK', difficulty: 'medium' },
  { name: 'Bangladesh', code: 'BD', difficulty: 'medium' },
  { name: 'China', code: 'CN', difficulty: 'easy' },
  { name: 'Japan', code: 'JP', difficulty: 'easy' },
  { name: 'South Korea', code: 'KR', difficulty: 'easy' },
  { name: 'North Korea', code: 'KP', difficulty: 'hard' },
  { name: 'Thailand', code: 'TH', difficulty: 'medium' },
  { name: 'Vietnam', code: 'VN', difficulty: 'medium' },
  { name: 'Indonesia', code: 'ID', difficulty: 'easy' },
  { name: 'Malaysia', code: 'MY', difficulty: 'medium' },
  { name: 'Singapore', code: 'SG', difficulty: 'medium' },
  { name: 'Philippines', code: 'PH', difficulty: 'medium' },
  { name: 'Australia', code: 'AU', difficulty: 'easy' },
  { name: 'New Zealand', code: 'NZ', difficulty: 'medium' },
  { name: 'Fiji', code: 'FJ', difficulty: 'hard' },
  { name: 'Papua New Guinea', code: 'PG', difficulty: 'hard' },
  { name: 'Kazakhstan', code: 'KZ', difficulty: 'hard' },
  { name: 'Uzbekistan', code: 'UZ', difficulty: 'easy' },
  { name: 'Afghanistan', code: 'AF', difficulty: 'hard' },
  { name: 'Mongolia', code: 'MN', difficulty: 'hard' },
  { name: 'Nepal', code: 'NP', difficulty: 'hard' },
  { name: 'Sri Lanka', code: 'LK', difficulty: 'hard' },
  { name: 'Israel', code: 'IL', difficulty: 'medium' },
  { name: 'Jordan', code: 'JO', difficulty: 'hard' },
  { name: 'Iraq', code: 'IQ', difficulty: 'hard' },
  { name: 'Syria', code: 'SY', difficulty: 'hard' },
  { name: 'Cuba', code: 'CU', difficulty: 'medium' },
  { name: 'Jamaica', code: 'JM', difficulty: 'medium' },
  { name: 'Dominican Republic', code: 'DO', difficulty: 'medium' },
]
