import { difficultyPoints, type Difficulty } from './countries'

export type PlayerFlagItem = {
  country: string
  code: string
  player: string
  difficulty: Difficulty
}

export const playerFlagItems: PlayerFlagItem[] = [
  { country: 'United States', code: 'US', player: 'Christian Pulisic', difficulty: 'easy' },
  { country: 'Canada', code: 'CA', player: 'Alphonso Davies', difficulty: 'easy' },
  { country: 'Mexico', code: 'MX', player: 'Hirving Lozano', difficulty: 'easy' },
  { country: 'Brazil', code: 'BR', player: 'Neymar', difficulty: 'easy' },
  { country: 'Argentina', code: 'AR', player: 'Lionel Messi', difficulty: 'easy' },
  { country: 'Chile', code: 'CL', player: 'Alexis Sanchez', difficulty: 'medium' },
  { country: 'Colombia', code: 'CO', player: 'James Rodriguez', difficulty: 'medium' },
  { country: 'Peru', code: 'PE', player: 'Paolo Guerrero', difficulty: 'medium' },
  { country: 'United Kingdom', code: 'GB', player: 'Harry Kane', difficulty: 'easy' },
  { country: 'Ireland', code: 'IE', player: 'Robbie Keane', difficulty: 'medium' },
  { country: 'France', code: 'FR', player: 'Kylian Mbappe', difficulty: 'easy' },
  { country: 'Germany', code: 'DE', player: 'Thomas Muller', difficulty: 'easy' },
  { country: 'Italy', code: 'IT', player: 'Gianluigi Donnarumma', difficulty: 'easy' },
  { country: 'Spain', code: 'ES', player: 'Alvaro Morata', difficulty: 'easy' },
  { country: 'Portugal', code: 'PT', player: 'Cristiano Ronaldo', difficulty: 'easy' },
  { country: 'Netherlands', code: 'NL', player: 'Virgil van Dijk', difficulty: 'medium' },
  { country: 'Belgium', code: 'BE', player: 'Kevin De Bruyne', difficulty: 'easy' },
  { country: 'Switzerland', code: 'CH', player: 'Granit Xhaka', difficulty: 'medium' },
  { country: 'Austria', code: 'AT', player: 'David Alaba', difficulty: 'medium' },
  { country: 'Poland', code: 'PL', player: 'Robert Lewandowski', difficulty: 'easy' },
  { country: 'Sweden', code: 'SE', player: 'Zlatan Ibrahimovic', difficulty: 'medium' },
  { country: 'Norway', code: 'NO', player: 'Erling Haaland', difficulty: 'easy' },
  { country: 'Denmark', code: 'DK', player: 'Christian Eriksen', difficulty: 'medium' },
  { country: 'Finland', code: 'FI', player: 'Teemu Pukki', difficulty: 'medium' },
  { country: 'Iceland', code: 'IS', player: 'Gylfi Sigurdsson', difficulty: 'hard' },
  { country: 'Russia', code: 'RU', player: 'Artem Dzyuba', difficulty: 'medium' },
  { country: 'Ukraine', code: 'UA', player: 'Andriy Yarmolenko', difficulty: 'medium' },
  { country: 'Turkey', code: 'TR', player: 'Hakan Calhanoglu', difficulty: 'medium' },
  { country: 'Greece', code: 'GR', player: 'Sokratis Papastathopoulos', difficulty: 'hard' },
  { country: 'Egypt', code: 'EG', player: 'Mohamed Salah', difficulty: 'easy' },
  { country: 'Morocco', code: 'MA', player: 'Achraf Hakimi', difficulty: 'medium' },
  { country: 'Algeria', code: 'DZ', player: 'Riyad Mahrez', difficulty: 'medium' },
  { country: 'Nigeria', code: 'NG', player: 'Victor Osimhen', difficulty: 'easy' },
  { country: 'Kenya', code: 'KE', player: 'Victor Wanyama', difficulty: 'hard' },
  { country: 'South Africa', code: 'ZA', player: 'Benni McCarthy', difficulty: 'hard' },
  { country: 'Ethiopia', code: 'ET', player: 'Saladin Said', difficulty: 'hard' },
  { country: 'Saudi Arabia', code: 'SA', player: 'Salem Al-Dawsari', difficulty: 'medium' },
  { country: 'United Arab Emirates', code: 'AE', player: 'Ali Mabkhout', difficulty: 'hard' },
  { country: 'Qatar', code: 'QA', player: 'Akram Afif', difficulty: 'medium' },
  { country: 'Iran', code: 'IR', player: 'Mehdi Taremi', difficulty: 'medium' },
  { country: 'India', code: 'IN', player: 'Sunil Chhetri', difficulty: 'medium' },
  { country: 'Pakistan', code: 'PK', player: 'Kaleemullah Khan', difficulty: 'hard' },
  { country: 'Bangladesh', code: 'BD', player: 'Jamal Bhuyan', difficulty: 'hard' },
  { country: 'China', code: 'CN', player: 'Wu Lei', difficulty: 'medium' },
  { country: 'Japan', code: 'JP', player: 'Takefusa Kubo', difficulty: 'easy' },
  { country: 'South Korea', code: 'KR', player: 'Son Heung-min', difficulty: 'easy' },
  { country: 'North Korea', code: 'KP', player: 'Han Kwang-song', difficulty: 'hard' },
  { country: 'Thailand', code: 'TH', player: 'Chanathip Songkrasin', difficulty: 'medium' },
  { country: 'Vietnam', code: 'VN', player: 'Nguyen Quang Hai', difficulty: 'medium' },
  { country: 'Indonesia', code: 'ID', player: 'Marselino Ferdinan', difficulty: 'medium' },
  { country: 'Malaysia', code: 'MY', player: 'Safawi Rasid', difficulty: 'hard' },
  { country: 'Singapore', code: 'SG', player: 'Fandi Ahmad', difficulty: 'hard' },
  { country: 'Philippines', code: 'PH', player: 'Neil Etheridge', difficulty: 'hard' },
  { country: 'Australia', code: 'AU', player: 'Sam Kerr', difficulty: 'easy' },
  { country: 'New Zealand', code: 'NZ', player: 'Chris Wood', difficulty: 'medium' },
  { country: 'Fiji', code: 'FJ', player: 'Roy Krishna', difficulty: 'hard' },
  { country: 'Papua New Guinea', code: 'PG', player: 'David Muta', difficulty: 'hard' },
  { country: 'Kazakhstan', code: 'KZ', player: 'Bakhtiyor Zaynutdinov', difficulty: 'hard' },
  { country: 'Uzbekistan', code: 'UZ', player: 'Eldor Shomurodov', difficulty: 'easy' },
  { country: 'Afghanistan', code: 'AF', player: 'Faysal Shayesteh', difficulty: 'hard' },
  { country: 'Mongolia', code: 'MN', player: 'Norjmoogiin Tsedenbal', difficulty: 'hard' },
  { country: 'Nepal', code: 'NP', player: 'Kiran Chemjong', difficulty: 'hard' },
  { country: 'Sri Lanka', code: 'LK', player: 'Sujan Perera', difficulty: 'hard' },
  { country: 'Israel', code: 'IL', player: 'Manor Solomon', difficulty: 'medium' },
  { country: 'Jordan', code: 'JO', player: 'Musa Al-Taamari', difficulty: 'hard' },
  { country: 'Iraq', code: 'IQ', player: 'Aymen Hussein', difficulty: 'hard' },
  { country: 'Syria', code: 'SY', player: 'Omar Khribin', difficulty: 'hard' },
  { country: 'Cuba', code: 'CU', player: 'Onel Hernandez', difficulty: 'hard' },
  { country: 'Jamaica', code: 'JM', player: 'Michail Antonio', difficulty: 'medium' },
  { country: 'Dominican Republic', code: 'DO', player: 'Junior Firpo', difficulty: 'medium' },
]

export const playerDifficultyPoints = difficultyPoints
